name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create test database
      run: |
        touch data/mock.sqlite3
    - name: Create table in test database
      run: |
        sqlite3 data/mock.sqlite3 < core/database/schema/schema.sql
    - name: Test with pytest
      run: |
        python -m unittest discover test "*_test.py" .
